# Generated by Django 2.0.7 on 2018-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10, null=True)),
                ('age', models.IntegerField(error_messages={'invalid': 'error'})),
                ('email', models.EmailField(help_text='emild', max_length=32, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('txt', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSex',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
            ],
        ),
    ]
