# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SomeOne\Desktop\python开发\python的包管理器\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 790)
        MainWindow.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(-1, -1, -1, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.myPackTable = QtWidgets.QTableWidget(self.tab_2)
        self.myPackTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.myPackTable.setObjectName("myPackTable")
        self.myPackTable.setColumnCount(5)
        self.myPackTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.myPackTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.myPackTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.myPackTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.myPackTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.myPackTable.setHorizontalHeaderItem(4, item)
        self.myPackTable.horizontalHeader().setCascadingSectionResizes(True)
        self.myPackTable.horizontalHeader().setStretchLastSection(False)
        self.myPackTable.verticalHeader().setCascadingSectionResizes(True)
        self.myPackTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.myPackTable, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 150))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout_3.addWidget(self.nameLabel, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.versionLabel = QtWidgets.QLabel(self.groupBox)
        self.versionLabel.setObjectName("versionLabel")
        self.gridLayout_3.addWidget(self.versionLabel, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.summaryLabel = QtWidgets.QLabel(self.groupBox)
        self.summaryLabel.setObjectName("summaryLabel")
        self.gridLayout_3.addWidget(self.summaryLabel, 2, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.homePageLabel = QtWidgets.QLabel(self.groupBox)
        self.homePageLabel.setObjectName("homePageLabel")
        self.gridLayout_3.addWidget(self.homePageLabel, 3, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 0, 1, 1)
        self.authorLabel = QtWidgets.QLabel(self.groupBox)
        self.authorLabel.setObjectName("authorLabel")
        self.gridLayout_3.addWidget(self.authorLabel, 4, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 5, 0, 1, 1)
        self.authorEmailLabel = QtWidgets.QLabel(self.groupBox)
        self.authorEmailLabel.setObjectName("authorEmailLabel")
        self.gridLayout_3.addWidget(self.authorEmailLabel, 5, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 1)
        self.licenseLabel = QtWidgets.QLabel(self.groupBox)
        self.licenseLabel.setObjectName("licenseLabel")
        self.gridLayout_3.addWidget(self.licenseLabel, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 7, 0, 1, 1)
        self.locationLabel = QtWidgets.QLabel(self.groupBox)
        self.locationLabel.setObjectName("locationLabel")
        self.gridLayout_3.addWidget(self.locationLabel, 7, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 8, 0, 1, 1)
        self.requiresLabel = QtWidgets.QLabel(self.groupBox)
        self.requiresLabel.setText("")
        self.requiresLabel.setObjectName("requiresLabel")
        self.gridLayout_3.addWidget(self.requiresLabel, 8, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 9, 0, 1, 1)
        self.requiresByLabel = QtWidgets.QLabel(self.groupBox)
        self.requiresByLabel.setText("")
        self.requiresByLabel.setObjectName("requiresByLabel")
        self.gridLayout_3.addWidget(self.requiresByLabel, 9, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 10, 0, 1, 3)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(20)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Package Manager of Python \\n"))
        self.label_3.setText(_translate("MainWindow", "Version --1.0"))
        self.label_2.setText(_translate("MainWindow", "Copyright © 2018 dangzhiteng. All rights reserved."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "All Packages"))
        self.checkBox.setText(_translate("MainWindow", "Display only updatable"))
        self.pushButton_2.setText(_translate("MainWindow", "Update All"))
        item = self.myPackTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.myPackTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Version"))
        item = self.myPackTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Latest"))
        item = self.myPackTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Update"))
        item = self.myPackTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Uninstall"))
        self.groupBox.setTitle(_translate("MainWindow", "Brief"))
        self.label_4.setText(_translate("MainWindow", "Name:"))
        self.nameLabel.setText(_translate("MainWindow", "pip"))
        self.label_6.setText(_translate("MainWindow", "Version:"))
        self.versionLabel.setText(_translate("MainWindow", "18.0"))
        self.label_9.setText(_translate("MainWindow", "Summary:"))
        self.summaryLabel.setText(_translate("MainWindow", "The PyPA recommended tool for installing Python packages."))
        self.label_8.setText(_translate("MainWindow", "Home-page:"))
        self.homePageLabel.setText(_translate("MainWindow", "https://pip.pypa.io/"))
        self.label_7.setText(_translate("MainWindow", "Author:"))
        self.authorLabel.setText(_translate("MainWindow", "The pip developers"))
        self.label_11.setText(_translate("MainWindow", "Author-email:"))
        self.authorEmailLabel.setText(_translate("MainWindow", "pypa-dev@groups.google.com"))
        self.label_12.setText(_translate("MainWindow", "License:"))
        self.licenseLabel.setText(_translate("MainWindow", "MIT"))
        self.label_13.setText(_translate("MainWindow", "Location:"))
        self.locationLabel.setText(_translate("MainWindow", "c:\\users\\someone\\appdata\\local\\programs\\python\\python35\\lib\\site-packages"))
        self.label_14.setText(_translate("MainWindow", "Requires:"))
        self.label_15.setText(_translate("MainWindow", "Required-by:"))
        self.pushButton.setText(_translate("MainWindow", "Help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "My Packages"))
        self.label.setText(_translate("MainWindow", "Package Manager of Python \n"
""))

